"""Updated casceade deletion to relationship on whole database

Revision ID: 462daec0cd49
Revises: 16f7482b0667
Create Date: 2025-06-14 22:59:08.265328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462daec0cd49'
down_revision: Union[str, None] = '16f7482b0667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('in_app_notifications_user_id_fkey', 'in_app_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'in_app_notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lesson_materials_lesson_id_fkey', 'lesson_materials', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_materials', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lessons_chapter_id_fkey', 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_question_multiple_choice_question_id_fkey', 'quiz_question_multiple_choice', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_question_multiple_choice', 'quiz_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_question_multiple_choice__question_multiple_choice_id_fkey', 'quiz_question_multiple_choice_options', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_question_multiple_choice_options', 'quiz_question_multiple_choice', ['question_multiple_choice_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_question_short_answer_question_id_fkey', 'quiz_question_short_answer', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_question_short_answer', 'quiz_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_question_single_choice_question_id_fkey', 'quiz_question_single_choice', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_question_single_choice', 'quiz_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_question_single_choice_opti_question_single_choice_id_fkey', 'quiz_question_single_choice_options', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_question_single_choice_options', 'quiz_question_single_choice', ['question_single_choice_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_questions_quiz_id_fkey', 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_questions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quizzes_lesson_id_fkey', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('support_ticket_ratings_ticket_id_fkey', 'support_ticket_ratings', type_='foreignkey')
    op.create_foreign_key(None, 'support_ticket_ratings', 'support_tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_achievements_user_id_fkey', 'user_achievements', type_='foreignkey')
    op.drop_constraint('user_achievements_achievement_id_fkey', 'user_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'user_achievements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_achievements', 'achievements', ['achievement_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_chapters_user_id_fkey', 'user_chapters', type_='foreignkey')
    op.drop_constraint('user_chapters_chapter_id_fkey', 'user_chapters', type_='foreignkey')
    op.create_foreign_key(None, 'user_chapters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_chapters', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_courses_course_id_fkey', 'user_courses', type_='foreignkey')
    op.drop_constraint('user_courses_user_id_fkey', 'user_courses', type_='foreignkey')
    op.create_foreign_key(None, 'user_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_courses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_lessons_user_id_fkey', 'user_lessons', type_='foreignkey')
    op.drop_constraint('user_lessons_lesson_id_fkey', 'user_lessons', type_='foreignkey')
    op.create_foreign_key(None, 'user_lessons', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_lessons', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_quiz_lives_user_id_fkey', 'user_quiz_lives', type_='foreignkey')
    op.create_foreign_key(None, 'user_quiz_lives', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_quizzes_user_id_fkey', 'user_quizzes', type_='foreignkey')
    op.drop_constraint('user_quizzes_quiz_id_fkey', 'user_quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'user_quizzes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_quizzes', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_xp_user_id_fkey', 'user_xp', type_='foreignkey')
    op.create_foreign_key(None, 'user_xp', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_xp', type_='foreignkey')
    op.create_foreign_key('user_xp_user_id_fkey', 'user_xp', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_quizzes', type_='foreignkey')
    op.drop_constraint(None, 'user_quizzes', type_='foreignkey')
    op.create_foreign_key('user_quizzes_quiz_id_fkey', 'user_quizzes', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key('user_quizzes_user_id_fkey', 'user_quizzes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_quiz_lives', type_='foreignkey')
    op.create_foreign_key('user_quiz_lives_user_id_fkey', 'user_quiz_lives', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_lessons', type_='foreignkey')
    op.drop_constraint(None, 'user_lessons', type_='foreignkey')
    op.create_foreign_key('user_lessons_lesson_id_fkey', 'user_lessons', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key('user_lessons_user_id_fkey', 'user_lessons', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_courses', type_='foreignkey')
    op.drop_constraint(None, 'user_courses', type_='foreignkey')
    op.create_foreign_key('user_courses_user_id_fkey', 'user_courses', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_courses_course_id_fkey', 'user_courses', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'user_chapters', type_='foreignkey')
    op.drop_constraint(None, 'user_chapters', type_='foreignkey')
    op.create_foreign_key('user_chapters_chapter_id_fkey', 'user_chapters', 'chapters', ['chapter_id'], ['id'])
    op.create_foreign_key('user_chapters_user_id_fkey', 'user_chapters', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.create_foreign_key('user_achievements_achievement_id_fkey', 'user_achievements', 'achievements', ['achievement_id'], ['id'])
    op.create_foreign_key('user_achievements_user_id_fkey', 'user_achievements', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'support_ticket_ratings', type_='foreignkey')
    op.create_foreign_key('support_ticket_ratings_ticket_id_fkey', 'support_ticket_ratings', 'support_tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_lesson_id_fkey', 'quizzes', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.create_foreign_key('quiz_questions_quiz_id_fkey', 'quiz_questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'quiz_question_single_choice_options', type_='foreignkey')
    op.create_foreign_key('quiz_question_single_choice_opti_question_single_choice_id_fkey', 'quiz_question_single_choice_options', 'quiz_question_single_choice', ['question_single_choice_id'], ['id'])
    op.drop_constraint(None, 'quiz_question_single_choice', type_='foreignkey')
    op.create_foreign_key('quiz_question_single_choice_question_id_fkey', 'quiz_question_single_choice', 'quiz_questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'quiz_question_short_answer', type_='foreignkey')
    op.create_foreign_key('quiz_question_short_answer_question_id_fkey', 'quiz_question_short_answer', 'quiz_questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'quiz_question_multiple_choice_options', type_='foreignkey')
    op.create_foreign_key('quiz_question_multiple_choice__question_multiple_choice_id_fkey', 'quiz_question_multiple_choice_options', 'quiz_question_multiple_choice', ['question_multiple_choice_id'], ['id'])
    op.drop_constraint(None, 'quiz_question_multiple_choice', type_='foreignkey')
    op.create_foreign_key('quiz_question_multiple_choice_question_id_fkey', 'quiz_question_multiple_choice', 'quiz_questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key('lessons_chapter_id_fkey', 'lessons', 'chapters', ['chapter_id'], ['id'])
    op.drop_constraint(None, 'lesson_materials', type_='foreignkey')
    op.create_foreign_key('lesson_materials_lesson_id_fkey', 'lesson_materials', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'in_app_notifications', type_='foreignkey')
    op.create_foreign_key('in_app_notifications_user_id_fkey', 'in_app_notifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
