"""Added order to chapters, lessons, quizquestions

Revision ID: 957393f3406b
Revises: 462daec0cd49
Create Date: 2025-06-15 15:21:23.242901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957393f3406b'
down_revision: Union[str, None] = '462daec0cd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('quiz_questions', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'order')
    op.drop_column('lessons', 'order')
    op.drop_column('chapters', 'order')
    # ### end Alembic commands ###
