"""Added order to LessonMaterial model

Revision ID: b03cc7392fa3
Revises: 957393f3406b
Create Date: 2025-06-15 16:14:03.202288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03cc7392fa3'
down_revision: Union[str, None] = '957393f3406b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_materials', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_materials', 'order')
    # ### end Alembic commands ###
