"""Added date of birth and gender

Revision ID: e8891d02dd48
Revises: 590dc29ece55
Create Date: 2025-06-12 01:26:55.510828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8891d02dd48'
down_revision: Union[str, None] = '590dc29ece55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('qty', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('achievements', 'qty')
    # ### end Alembic commands ###
